# Generated by Django 4.0.2 on 2022-02-25 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 13, 55, 36, 600835)),
        ),
    ]
